// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghzlurxensmtqakysqtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdoemx1cnhlbnNtdHFha3lzcXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTgwNzUsImV4cCI6MjA2NDE3NDA3NX0.csh4hJe77GU0BA8IGfM5nFIPorYzyz5PBr50dJ4PLyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);